# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-05 03:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20181228_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 3, 3, 51, 273689, tzinfo=utc)),
        ),
    ]
