# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-08 06:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190108_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 6, 2, 9, 288833, tzinfo=utc)),
        ),
    ]
