# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-08 07:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190108_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 7, 30, 31, 448100, tzinfo=utc)),
        ),
    ]
