# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-09 15:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190108_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 15, 20, 31, 423831, tzinfo=utc)),
        ),
    ]
