# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-09 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20190109_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 15, 27, 5, 485370, tzinfo=utc)),
        ),
    ]
