# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-10 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20190110_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 10, 9, 50, 21, 450662, tzinfo=utc)),
        ),
    ]
